import{Router}from"express";import{requireUser,type AuthenticatedRequest}from"../auth/requireUser.js";import{requireAdmin}from"../auth/requireAdmin.js";import{adminClient}from"../lib/supabase.js";const router=Router();router.use(requireUser,requireAdmin);
router.get("/summary",async(_req,res,next)=>{try{const db=adminClient(),start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);const[{count:users},{data:periods},{data:subs},{count:conversations}]=await Promise.all([db.from("profiles").select("id",{count:"exact",head:true}),db.from("usage_periods").select("used_duration_ms,total_tokens,estimated_cost_micros").gte("period_start",start.toISOString()),db.from("subscriptions").select("plan_id,status"),db.from("conversations").select("id",{count:"exact",head:true}).gte("created_at",start.toISOString())]);const usage=(periods??[]).reduce((a,x)=>({minutes:a.minutes+Number(x.used_duration_ms)/60000,tokens:a.tokens+Number(x.total_tokens),costMicros:a.costMicros+Number(x.estimated_cost_micros)}),{minutes:0,tokens:0,costMicros:0});res.json({ok:true,metrics:{users:users??0,conversations:conversations??0,activeSubscriptions:(subs??[]).filter(x=>["active","trialing"].includes(x.status)).length,proUsers:(subs??[]).filter(x=>x.plan_id==="pro"&&["active","trialing"].includes(x.status)).length,...usage}})}catch(e){next(e)}});
router.get("/daily",async(req,res,next)=>{try{const days=Math.max(7,Math.min(Number(req.query.days)||30,90)),since=new Date(Date.now()-days*86400000).toISOString(),{data,error}=await adminClient().from("daily_usage").select("day,requests,duration_ms,total_tokens,estimated_cost_micros").gte("day",since).order("day");if(error)throw error;const grouped=new Map<string,any>();for(const x of data??[]){const day=String(x.day).slice(0,10),v=grouped.get(day)||{day,requests:0,minutes:0,tokens:0,costMicros:0};v.requests+=Number(x.requests);v.minutes+=Number(x.duration_ms)/60000;v.tokens+=Number(x.total_tokens);v.costMicros+=Number(x.estimated_cost_micros);grouped.set(day,v)}res.json({ok:true,days:[...grouped.values()]})}catch(e){next(e)}});
router.get("/users",async(req,res,next)=>{try{const q=String(req.query.q??"").trim().slice(0,100),db=adminClient();let query=db.from("profiles").select("id,email,full_name,role,access_status,created_at,subscriptions(plan_id,status,current_period_end),usage_periods(used_duration_ms,total_tokens,estimated_cost_micros,period_start)").order("created_at",{ascending:false}).limit(100);if(q)query=query.ilike("email",`%${q}%`);const{data,error}=await query;if(error)throw error;res.json({ok:true,users:data})}catch(e){next(e)}});
router.get("/plans",async(_req,res,next)=>{try{const{data,error}=await adminClient().from("plans").select("*").order("price_cents");if(error)throw error;res.json({ok:true,plans:data,stripeConfigured:Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_PRICE_ID_PRO)})}catch(e){next(e)}});
router.patch("/plans/:id",async(req,res,next)=>{try{const actor=(req as unknown as AuthenticatedRequest).auth.userId,changes={name:String(req.body?.name??"").trim().slice(0,80),description:String(req.body?.description??"").trim().slice(0,240),monthly_minutes:Math.max(1,Number(req.body?.monthlyMinutes)||1),daily_minutes:Math.max(1,Number(req.body?.dailyMinutes)||1),monthly_cost_limit_micros:Math.max(1,Number(req.body?.costLimitMicros)||1),price_cents:Math.max(0,Number(req.body?.priceCents)||0),active:Boolean(req.body?.active)};const db=adminClient(),{data,error}=await db.from("plans").update(changes).eq("id",req.params.id).select().single();if(error)throw error;await db.from("audit_log").insert({actor_user_id:actor,action:"plan.update",target_type:"plan",target_id:req.params.id,metadata:changes});res.json({ok:true,plan:data})}catch(e){next(e)}});
router.patch("/users/:id/plan",async(req,res,next)=>{try{const actor=(req as unknown as AuthenticatedRequest).auth.userId,planId=String(req.body?.planId??"");if(!["free","pro"].includes(planId))return res.status(400).json({ok:false,message:"Invalid plan."});const db=adminClient(),{data,error}=await db.from("subscriptions").update({plan_id:planId,status:"active",updated_at:new Date().toISOString()}).eq("user_id",req.params.id).select().single();if(error)throw error;await db.from("audit_log").insert({actor_user_id:actor,action:"subscription.plan_change",target_type:"user",target_id:req.params.id,metadata:{planId}});res.json({ok:true,subscription:data})}catch(e){next(e)}});export default router;



